# Generated by Django 5.2.6 on 2025-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_student_e_signature_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='form_photo',
            field=models.ImageField(blank=True, null=True, upload_to='form_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
