# Generated by Django 5.2.6 on 2025-09-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_student_form_photo_alter_student_e_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='no', max_length=20, null=True),
        ),
    ]
